version: "3"

services:
  app:
    depends_on:
      - db
    env_file: app.env

  db:
    image: postgres:12
    env_file: app.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
