version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
    ports:
      - "8000:8000/tcp"
    volumes:
      - ./src:/app

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "40080:80/tcp"
    environment:
      - PGADMIN_DEFAULT_EMAIL=asdf@asdf.com
      - PGADMIN_DEFAULT_PASSWORD=1q2w3e4r!
