version: "3"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    depends_on:
      - db
    env_file: backend.env

  db:
    image: postgres:12
    env_file: backend.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
